<?php

/**
 * Script to fix ContactGroupResolver to use Doctrine entities
 * 
 * This script modifies the ContactGroupResolver class to create a Doctrine entity
 * instead of a legacy model when creating a contact group.
 */

require_once __DIR__ . '/../vendor/autoload.php';

// Define the file to modify
$filePath = __DIR__ . '/../src/GraphQL/Resolvers/ContactGroupResolver.php';

// Read the file content
$content = file_get_contents($filePath);

// Create a backup of the original file
file_put_contents($filePath . '.bak', $content);
echo "Created backup of original file at {$filePath}.bak\n";

// Replace the legacy model import with the Doctrine entity import
$content = str_replace(
    'use App\Models\ContactGroup;',
    'use App\Entities\ContactGroup;',
    $content
);

$content = str_replace(
    'use App\Models\Contact;',
    'use App\Entities\Contact;',
    $content
);

// Replace the legacy model creation with Doctrine entity creation in mutateCreateContactGroup method
$oldCode = <<<'EOD'
            // Create a new contact group model instance
            $group = new ContactGroup(
                0, // ID will be generated by the database
                $userId,
                $name,
                $args['description'] ?? null
                // createdAt/updatedAt handled by model/repository
            );
EOD;

$newCode = <<<'EOD'
            // Create a new contact group entity instance
            $group = new ContactGroup();
            $group->setUserId($userId);
            $group->setName($name);
            $group->setDescription($args['description'] ?? null);
            $group->setCreatedAt(new \DateTime());
            $group->setUpdatedAt(new \DateTime());
EOD;

$content = str_replace($oldCode, $newCode, $content);

// Write the modified content back to the file
file_put_contents($filePath, $content);
echo "Updated {$filePath} to use Doctrine entity instead of legacy model\n";

// Verify the changes
$newContent = file_get_contents($filePath);
if (
    strpos($newContent, 'use App\Entities\ContactGroup;') !== false &&
    strpos($newContent, '$group = new ContactGroup();') !== false
) {
    echo "Verification successful: File was correctly modified\n";
} else {
    echo "Verification failed: File was not correctly modified\n";
}

echo "\nDone.\n";
